server.port=8089
spring.datasource.url=jdbc:mysql://localhost:3307/buildingblock
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect
#by default it is always set it to never  this is for remove traces in exception when using devtools then verify the response
server.error.include-stacktrace=never